apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-app
spec:
  template:
    spec:
      containers:
        - name: solver-app
          env:
            - name: LOG_LEVEL
              value: "DEBUG"  # Change log level for development
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
