apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: solver-app
    newName: myacrname.azurecr.io/solver-app
    newTag: latest
